# Generated by Django 4.2.3 on 2023-09-19 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('role', models.CharField(choices=[('member', 'Thành viên'), ('admin', 'Quản trị viên'), ('approver', 'Người kiểm duyệt')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_title', models.CharField(max_length=200)),
                ('journal_name', models.CharField(max_length=200)),
                ('issn_isbn', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('publication_type', models.CharField(max_length=100)),
                ('authors', models.TextField()),
                ('attachments', models.FileField(upload_to='journal_publication_attachments/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PublishedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('authors', models.TextField()),
                ('publisher', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('isbn', models.CharField(max_length=20)),
                ('field_of_study', models.CharField(max_length=100)),
                ('attachments', models.FileField(upload_to='published_book_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_title', models.CharField(max_length=200)),
                ('award_level', models.CharField(max_length=50)),
                ('award_category', models.CharField(max_length=100)),
                ('authors', models.TextField()),
                ('award_rank', models.CharField(choices=[('first', 'Nhất'), ('second', 'Nhì'), ('third', 'Ba'), ('encouragement', 'Khuyến khích')], max_length=20)),
                ('award_received_date', models.DateField()),
                ('attachments', models.FileField(upload_to='research_award_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('funding_level', models.CharField(max_length=50)),
                ('research_type', models.CharField(max_length=100)),
                ('lead_unit', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('team_members', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('approval_date', models.DateField()),
                ('approved_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('completed', 'Đã hoàn thành'), ('in_progress', 'Đang thực hiện'), ('not_started', 'Chưa thực hiện')], max_length=20)),
                ('attachments', models.FileField(upload_to='research_topic_attachments/')),
                ('academic_year', models.CharField(max_length=10)),
                ('research_hours', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyTransferProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('authors', models.TextField()),
                ('transfer_company', models.CharField(max_length=200)),
                ('transfer_contract_id', models.CharField(max_length=50)),
                ('signed_contract_id', models.CharField(max_length=50)),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_signing_date', models.DateField()),
                ('attachments', models.FileField(upload_to='technology_transfer_project_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchTopicRegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_topic_id', models.PositiveIntegerField()),
                ('assigned_role', models.CharField(max_length=100)),
                ('registration_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành')], max_length=20)),
                ('approver_id', models.PositiveIntegerField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProposalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_topic_id', models.PositiveIntegerField()),
                ('submission_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành')], max_length=20)),
                ('approver_id', models.PositiveIntegerField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchActivityDeclarationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.PositiveIntegerField()),
                ('activity_type', models.CharField(max_length=100)),
                ('assigned_role', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=10)),
                ('declaration_date', models.DateField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('approver_id', models.PositiveIntegerField()),
                ('research_hours', models.PositiveIntegerField()),
                ('submission_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_degree', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('education_history', models.TextField()),
                ('work_history', models.TextField()),
                ('research_activities', models.TextField()),
                ('research_hours', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
