# Generated by Django 4.2.3 on 2023-08-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_code',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_code',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='reference_code',
        ),
        migrations.RemoveField(
            model_name='researchtopic',
            name='topic_code',
        ),
    ]
