# Generated by Django 4.2.3 on 2023-08-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0002_remove_article_article_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='description',
            new_name='abstract',
        ),
        migrations.RenameField(
            model_name='researchtopic',
            old_name='study_hours_required',
            new_name='study_hours',
        ),
        migrations.RemoveField(
            model_name='research',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='research',
            name='study_status',
        ),
        migrations.AddField(
            model_name='researchtopic',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Chưa kiểm phê duyệt'), ('Approved', 'Đã kiểm phê duyệt')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='researchtopic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchtopic',
            name='study_status',
            field=models.CharField(choices=[('InProgress', 'Đang tiến hành'), ('Completed', 'Đã hoàn thành')], default='InProgress', max_length=20),
        ),
    ]
