# Generated by Django 4.2.3 on 2023-09-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicprofile',
            name='research_hours',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='researchtopic',
            name='academic_year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='researchtopic',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchtopic',
            name='approved_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='researchtopic',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='research_topic_attachments/'),
        ),
        migrations.AlterField(
            model_name='researchtopic',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='researchtopic',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchtopic',
            name='lead_unit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='researchtopic',
            name='research_hours',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='researchtopic',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchtopic',
            name='team_members',
            field=models.TextField(null=True),
        ),
    ]
