# Generated by Django 4.2.3 on 2023-09-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0003_remove_academicprofile_research_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtopic',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
